### ISSUE TITLE
增加ASPP模块后，val_loss变成nan 可能是什么原因

### ISSUE THREAD

**Issue by 490163917** [qxde01/gastric-cancer-detect#1]
我在EfficientNetB4网络的输出增加了ASPP模块，训练集loss正常，但是测试集变成了nan,请问可能是什么原因？
469/469 [==============================] - 249s 532ms/step - loss: 6.4746 - d_loss: 1.0028 - d1_loss: 1.1757 - d2_loss: 1.1508 - d3_loss: 1.0595 - d4_loss: 1.0523 - d5_loss: 1.0335 - d_DICE: 0.4591 - d1_DICE: 0.3353 - d2_DICE: 0.3365 - d3_DICE: 0.4171 - d4_DICE: 0.4236 - d5_DICE: 0.4739 - val_loss: nan - val_d_loss: nan - val_d1_loss: nan - val_d2_loss: nan - val_d3_loss: nan - val_d4_loss: nan - val_d5_loss: nan - val_d_DICE: 0.0000e+00 - val_d1_DICE: 0.0000e+00 - val_d2_DICE: 0.0000e+00 - val_d3_DICE: 0.0000e+00 - val_d4_DICE: 0.0000e+00 - val_d5_DICE: 0.0000e+00

**Comment by qxde01** [comment]
猜测可能是dice_loss引起的，dice下降不是平滑的，可以先用bce或focal后面再加上dice
